---
tls_cert_path: "../../../files/tls"
network_interface: "eth1"
nomad_region: "dc1"
nomad_datacenter: "global"
# overprovision nomad
nomad_client_total_memory: 32000
nomad_client_total_cpu_mhz: 32000
nomad_podman_plugin_url: "https://releases.hashicorp.com/nomad-driver-podman/0.5.2/nomad-driver-podman_0.5.2_linux_amd64.zip"
nomad_bootstrap_expect: 2
nomad_encrypt_key: "5iy0jYaeCPZCSNnweHtsdpme4DOU+0cIyxtilb8mqSI="
nomad_tls_files:
  - nomad-ca.pem
  - nomad-ca-key.pem
  - nomad/client.pem
  - nomad/client-key.pem
  - nomad/server.pem
  - nomad/server-key.pem
nomad_consul_tls_files:
  - src: consul-ca.pem
    dest: consul-ca.pem
  - src: consul/client.pem
    dest: consul.pem
  - src: consul/client-key.pem
    dest: consul-key.pem
consul_encrypt_key: "X81wFZh3MkAgTHlq3OeNRqpmXrr1E4V6RYibWf9rxNI="
consul_tls_files:
  - consul-ca.pem
  - consul-ca-key.pem
  - consul/client.pem
  - consul/client-key.pem
  - consul/server.pem
  - consul/server-key.pem
consul_datacenter: "dc1"
consul_retry_join:
  - 192.168.60.14
  - 192.168.60.15
consul_bootstrap_expect: 2
podman_sock_path: "/var/run/podman/podman.sock"

